"""ARCHIVED v2 report generator.

This preserves the raster-GT / eval2d_v2_hungarian visual audit only.  Current
v3 official-GT figures are generated by ``gen_v3_visuals_pillow.py``.  This
script must not overwrite the current-facing root ``RESULTS_2D.md``.
"""
import glob, os, pickle, sys, textwrap
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.font_manager as _fm
for _p in ("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",):  # 讓 matplotlib 能畫繁中，不出方框
    if os.path.exists(_p):
        try:
            _fm.fontManager.addfont(_p)
            matplotlib.rcParams["font.family"] = "sans-serif"
            matplotlib.rcParams["font.sans-serif"] = ["Noto Sans CJK TC", "Noto Sans CJK JP", "DejaVu Sans"]
            matplotlib.rcParams["axes.unicode_minus"] = False
        except Exception:
            pass
        break
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from metrics import prf, align_levels
from canonical_io import load_canonical
import json

ROOT = "/home/ado/storage/HouseLayout3D"
BASE = f"{ROOT}/outputs/eval2d/baselines/watershed_v3_pre_report"
CANON = f"{ROOT}/outputs/eval2d/canonical/watershed_v3_pre_report"
VIZ = f"{BASE}/eval2d_v2_hungarian/visualizations"
EVAL2D_VERSION = "eval2d_v2_hungarian_archived"
os.makedirs(VIZ, exist_ok=True)
scores = pickle.load(open(f"{BASE}/eval2d_v2_hungarian/scores.pkl", "rb"))
scenes = sorted(scores)
per = {S: prf(*scores[S]["A"]["room"])["f1"] for S in scenes}


def draw(ax, floor, title, edges=None, ids=True):
    cents = {}
    for i, r in enumerate(floor["rooms"]):
        p = np.asarray(r["poly"]); ax.fill(p[:, 0], p[:, 1], alpha=.45, color=cm.tab20(i % 20), lw=.6, ec="#333")
        cents[r["idx"]] = p.mean(0)
        if ids:
            ax.text(*p.mean(0), f"R{r['idx']}\n{str(r.get('type','?'))[:8]}", ha="center", va="center",
                    fontsize=8.5, fontweight="bold", color="#111")
    for d in floor["doors"]:
        s = np.asarray(d["seg"]); ax.plot(s[:, 0], s[:, 1], "-", c="crimson", lw=3, zorder=5)
    for e in (edges or []):
        a, b = e["rooms"]
        if e.get("kind") == "room-room" and a in cents and b in cents:
            ax.plot([cents[a][0], cents[b][0]], [cents[a][1], cents[b][1]], "-", c="0.35", lw=1, zorder=3)
    ax.set_aspect("equal"); ax.set_title(title, fontsize=11)
    ax.set_xlabel("x (m)", fontsize=9); ax.set_ylabel("y (m)", fontsize=9)
    ax.tick_params(labelsize=8)
    ax.grid(alpha=.10, lw=.5)


def level_gt(gt, L):
    """GT 某層：只取評估集合房間（in_roomset 且非 stairs），與 evaluator 一致。"""
    return {"rooms": [r for r in gt["rooms"] if r["level"] == L and r.get("in_roomset") and not r.get("is_stairs")],
            "doors": [d for d in gt["doors"] if d["level"] == L],
            "edges": [e for e in gt.get("edges", []) if e.get("level") == L]}

def level_pred(pr, L):
    return {"rooms": [r for r in pr["rooms"] if r["level"] == L],
            "doors": [d for d in pr["doors"] if d["level"] == L],
            "edges": [e for e in pr.get("edges", []) if e.get("level") == L]}


def viz(scene, tag, prefer_upper=False):
    gt = pickle.load(open(f"{BASE}/gt/{scene}.pkl", "rb"))
    pr = pickle.load(open(f"{BASE}/pred/{scene}.pkl", "rb"))
    lvl_map = align_levels(gt["lvl_z"], pr.get("level_z", {}))   # {gt_L: pred_L}（evaluator 同法）
    if not lvl_map:
        return None
    pairs = sorted(lvl_map.items())
    if prefer_upper and len(pairs) > 1:                          # 取「非最低」中 GT 房最多的對齊層對
        gt_L, pred_L = max(pairs[1:], key=lambda pp: len(level_gt(gt, pp[0])["rooms"]))
    else:
        gt_L, pred_L = pairs[0]
    g1, p1 = level_gt(gt, gt_L), level_pred(pr, pred_L)
    nlvl_g = len(gt["lvl_z"]); nlvl_p = len(pr.get("level_z", {}))
    # 16:9 / 1920×1080，直接放投影片仍可讀。
    fig, ax = plt.subplots(1, 2, figsize=(16, 9))
    draw(ax[0], g1, f"GT — {scene} · L{gt_L} (evaluator 排除 stairs)", g1.get("edges"))
    draw(ax[1], p1, f"PRED — {scene} · L{pred_L}", p1.get("edges"))
    fig.suptitle(f"[{tag}] {scene}  ·  對齊層 GT L{gt_L} ↔ PRED L{pred_L}  "
                 f"(GT {nlvl_g} 層 / PRED {nlvl_p} 層)  ·  {EVAL2D_VERSION}", fontsize=13)
    fig.text(0.5, 0.028, f"Room-F1={per[scene]:.2f} · IoU={np.mean(scores[scene]['iou'] or [0]):.2f}  "
             f"（scene aggregate；非此單層）", ha="center", fontsize=10, color="#4c5661")
    fig.text(0.5, 0.006, "PRELIMINARY annotated-floorplan baseline · watershed_v3 (local engineering variant) · "
             "connectivity DERIVED (not annotated) · room types UNRELIABLE · 紅=doors 灰=derived edges 尺=metres",
             ha="center", fontsize=9, color="#a9700f")
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    out = f"{VIZ}/{tag}_{scene}.png"; fig.savefig(out, dpi=120, facecolor="white"); plt.close(fig)
    return out


order = sorted(per, key=per.get)
worst, med, best = order[0], order[len(order)//2], order[-1]
multi = max(scenes, key=lambda s: len(set(r["level"] for r in
           pickle.load(open(f"{BASE}/pred/{s}.pkl", "rb"))["rooms"])))
vp = {"best": viz(best, "best"), "median": viz(med, "median"),
      "worst": viz(worst, "worst"), "multi_level": viz(multi, "multi_level", prefer_upper=True)}


def metric_f1(scene, tier, key):
    return prf(*scores[scene][tier].get(key, [0, 0, 0]))["f1"]


def build_error_analysis():
    """產生投影片用 16-scene distribution + diagnostic flags（不調 method/threshold）。"""
    diagnostics = []
    for scene in scenes:
        gt = pickle.load(open(f"{BASE}/gt/{scene}.pkl", "rb"))
        pred = pickle.load(open(f"{BASE}/pred/{scene}.pkl", "rb"))
        gt_rooms = sum(r.get("in_roomset") and not r.get("is_stairs") for r in gt["rooms"])
        pred_rooms = len(pred["rooms"])
        lvl_map = align_levels(gt["lvl_z"], pred.get("level_z", {}))
        unmatched_gt = len(set(gt["lvl_z"]) - set(lvl_map))
        unmatched_pred = len(set(pred.get("level_z", {})) - set(lvl_map.values()))
        room_f1 = per[scene]
        matched_iou = float(np.mean(scores[scene]["iou"] or [0]))
        door_f1 = metric_f1(scene, "B", "doors@0.5")
        edge_f1 = metric_f1(scene, "C", "all")
        flags = {
            # 只是透明的 diagnostic rules，不是新 benchmark pass/fail threshold。
            "geometry_good": room_f1 >= 0.65 and matched_iou >= 0.75,
            "under_segmented": pred_rooms <= gt_rooms - 3,
            "level_mismatch_or_extra": unmatched_gt > 0 or unmatched_pred > 0,
            "door_or_topology_weak": door_f1 < 0.25 or edge_f1 < 0.15,
        }
        diagnostics.append({
            "scene": scene, "room_f1": room_f1, "matched_room_iou": matched_iou,
            "pred_rooms": pred_rooms, "gt_rooms": gt_rooms,
            "gt_levels": len(gt["lvl_z"]), "pred_levels": len(pred.get("level_z", {})),
            "aligned_levels": len(lvl_map), "unmatched_gt_levels": unmatched_gt,
            "unmatched_pred_levels": unmatched_pred,
            "doors_0.5_f1": door_f1, "edge_all_f1": edge_f1, "flags": flags,
        })

    rules = {
        "geometry_good": "Room F1≥0.65 且 matched IoU≥0.75",
        "under_segmented": "pred room count ≤ GT−3",
        "level_mismatch_or_extra": "至少一個 GT/PRED level 未對齊",
        "door_or_topology_weak": "Doors@0.5<0.25 或 edge_all<0.15",
    }
    out_json = f"{BASE}/eval2d_v2_hungarian/error_analysis.json"
    with open(out_json, "w") as f:
        json.dump({"status": "diagnostic_nonexclusive_flags", "rules": rules,
                   "per_scene": diagnostics}, f, ensure_ascii=False, indent=2)

    ordered = sorted(diagnostics, key=lambda d: d["room_f1"])
    fig = plt.figure(figsize=(16, 9))
    gs = fig.add_gridspec(2, 2, width_ratios=[1.12, 1], height_ratios=[1.2, .8],
                          hspace=.28, wspace=.25)
    ax_bar = fig.add_subplot(gs[:, 0])
    ax_scatter = fig.add_subplot(gs[0, 1])
    ax_flags = fig.add_subplot(gs[1, 1])

    y = np.arange(len(ordered))
    colors = ["#3f7a4b" if d["room_f1"] >= .65 else
              "#bd812f" if d["room_f1"] >= .5 else "#a94a42" for d in ordered]
    ax_bar.barh(y, [d["room_f1"] for d in ordered], color=colors, alpha=.9)
    ax_bar.axvline(.5, color="#5c6670", ls="--", lw=1.2, label="Room F1=0.5 reference")
    ax_bar.set_yticks(y, [d["scene"] for d in ordered], fontsize=8)
    ax_bar.set_xlim(0, 1)
    ax_bar.set_xlabel("Room F1 @ IoU>0.5")
    ax_bar.set_title("16-scene Room F1 distribution（不是只看平均）", fontsize=12)
    ax_bar.grid(axis="x", alpha=.2)
    ax_bar.legend(loc="lower right", fontsize=9)
    for yi, d in enumerate(ordered):
        ax_bar.text(d["room_f1"] + .012, yi, f"{d['room_f1']:.2f}", va="center", fontsize=8)

    # Fixed offsets keep the dense middle cluster legible on a 16:9 slide.
    # They are presentation-only and do not depend on metric thresholds.
    label_offsets = {
        "17DRP": (-12, -18), "1LXtF": (6, 6), "2t7WU": (-12, 7),
        "5LpN3": (-12, 7), "HxpKQ": (-7, 7), "JeFG2": (6, -16),
        "JmbYf": (7, -17), "S9hNv": (7, 7), "TbHJr": (-18, -14),
        "WYY7i": (11, -3), "YFuZg": (-10, -17), "e9zR4": (7, 8),
        "i5noy": (-5, 9), "jtcxE": (-16, 9), "p5wJj": (7, 12),
        "r47D5": (12, 9),
    }
    for d in diagnostics:
        color = "#3f7a4b" if d["flags"]["geometry_good"] else "#a9700f"
        marker = "X" if d["flags"]["level_mismatch_or_extra"] else "o"
        ax_scatter.scatter(d["room_f1"], d["matched_room_iou"], s=55, c=color,
                           marker=marker, edgecolor="white", linewidth=.6)
        label = d["scene"][:5]
        offset = label_offsets[label]
        ax_scatter.annotate(
            label, (d["room_f1"], d["matched_room_iou"]), xytext=offset,
            textcoords="offset points", fontsize=7,
            ha="left" if offset[0] >= 0 else "right",
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": .72, "pad": .15},
        )
    ax_scatter.set_xlim(0, 1); ax_scatter.set_ylim(.68, .94)
    ax_scatter.set_xlabel("Room F1（coverage + one-to-one matching）")
    ax_scatter.set_ylabel("matched-room conditional IoU")
    ax_scatter.set_title("為何 F1 低、conditional IoU 仍可能高", fontsize=12)
    ax_scatter.grid(alpha=.2)
    ax_scatter.text(.03, .70, "例：HxpK 只對上少數房，\n所以 F1 低但 matched IoU 高",
                    fontsize=9, color="#7f302b", va="bottom")

    ax_flags.axis("off")
    flag_labels = [
        ("geometry_good", "Geometry good"),
        ("under_segmented", "Under-segmented"),
        ("level_mismatch_or_extra", "Level mismatch / extra"),
        ("door_or_topology_weak", "Door / topology weak"),
    ]
    ax_flags.set_title("Error taxonomy（non-exclusive diagnostic flags）", fontsize=12, loc="left")
    for row, (key, label) in enumerate(flag_labels):
        hit = [d["scene"][:5] for d in diagnostics if d["flags"][key]]
        ypos = .86 - row * .24
        ax_flags.text(.01, ypos, f"{label}  {len(hit)}/16", fontsize=10, fontweight="bold",
                      color="#3f7a4b" if key == "geometry_good" else "#7f302b")
        ax_flags.text(.01, ypos - .085, textwrap.fill(", ".join(hit) or "—", width=58),
                      fontsize=8.5, color="#4c5661", va="top")

    fig.suptitle("Preliminary 2D floorplan error analysis · frozen watershed_v3 baseline",
                 fontsize=15)
    fig.text(.5, .018,
             "Flags 是解讀規則、不是調分 threshold；scene ID 在 scatter/flags 縮寫前 5 碼。"
             " matched IoU 只看成功配對房，不能單獨代表完整 floorplan。",
             ha="center", fontsize=9.5, color="#4c5661")
    fig.subplots_adjust(left=.15, right=.98, bottom=.09, top=.90)
    out_fig = f"{VIZ}/error_analysis_summary.png"
    fig.savefig(out_fig, dpi=120, facecolor="white")
    plt.close(fig)
    return diagnostics, rules, out_fig, out_json


diagnostics, diagnostic_rules, error_fig, error_json = build_error_analysis()

# current-facing RESULTS_2D.md（v2 数字，preliminary）
def agg(key, sub):
    t = [0, 0, 0]
    for S in scores:
        v = scores[S][key].get(sub, [0, 0, 0]); t = [t[i]+v[i] for i in range(3)]
    return prf(*t)
alliou = [x for S in scores for x in scores[S]["iou"]]
good = sum(v >= 0.5 for v in per.values())
L = ["# RESULTS_2D — 2D Floorplan Evaluation (watershed_v3, PRELIMINARY)\n",
     f"> evaluator＝**{EVAL2D_VERSION}**（deterministic Hungarian）· predictions＝frozen `watershed_v3_pre_report`",
     "> `watershed_v3` 是 **local engineering variant**（非 paper-spec）· connectivity＝**derived**（portals=0）",
     "> 此為 **PRELIMINARY annotated-floorplan baseline**，非 strict paper reproduction。\n",
     "## Tier A — 幾何\n| 指標 | F1 | 備註 |\n|---|---|---|",
     f"| **Room @IoU>0.5** | **{agg('A','room')['f1']:.3f}** | P {agg('A','room')['p']:.2f} R {agg('A','room')['r']:.2f} |",
     f"| mean Room IoU (**matched rooms only**, n={len(alliou)}) | {np.mean(alliou):.3f} | conditional mean（僅成功配對房，非全房平均）|",
     f"| Corner F1 @0.1/0.2/0.3m | {agg('A','corner@0.1')['f1']:.2f}/{agg('A','corner@0.2')['f1']:.2f}/{agg('A','corner@0.3')['f1']:.2f} | 受 GT rasterization/RDP bias 影響，**不可直接與 clean-CAD 256px 指標比** |",
     f"| Angle F1 @0.1m | {agg('A','angle@0.1')['f1']:.2f} | — |",
     "\n## Tier B — 語意\n| 指標 | F1 |\n|---|---|",
     f"| Room+type | {agg('B','room+type')['f1']:.3f}（CLIP 房型不可靠）|",
     f"| Doors @0.2/0.5m | {agg('B','doors@0.2')['f1']:.2f}/{agg('B','doors@0.5')['f1']:.2f} |",
     "\n## Tier C — 拓撲（derived GT，權重下調）\n| edge | P | R | F1 |\n|---|---|---|---|"]
for k in ("room_room", "outside", "all"):
    m = agg("C", k); L.append(f"| {k} | {m['p']:.2f} | {m['r']:.2f} | {m['f1']:.3f} |")
L += [f"\n## 分布\n{good}/16 棟 Room F1 ≥ 0.5 · 中位 {np.median(list(per.values())):.2f} · "
      f"best {best} {per[best]:.2f} / worst {worst} {per[worst]:.2f}",
      "\n## 視覺化（frozen baseline）", ] + [f"- {t}: `{os.path.relpath(p, ROOT)}`" for t, p in vp.items()]
flag_count = {key: sum(d["flags"][key] for d in diagnostics) for key in diagnostic_rules}
L += ["\n## Error analysis（diagnostic flags，彼此可重疊）",
      f"- 圖：`{os.path.relpath(error_fig, ROOT)}`",
      f"- geometry good：{flag_count['geometry_good']}/16（{diagnostic_rules['geometry_good']}）",
      f"- under-segmented：{flag_count['under_segmented']}/16（{diagnostic_rules['under_segmented']}）",
      f"- level mismatch／extra：{flag_count['level_mismatch_or_extra']}/16（{diagnostic_rules['level_mismatch_or_extra']}）",
      f"- door／topology weak：{flag_count['door_or_topology_weak']}/16（{diagnostic_rules['door_or_topology_weak']}）",
      "- 這些是透明的 error-analysis rules，不是為提高分數設定的新 pass/fail thresholds。"]

gt_audit_path = f"{BASE}/eval2d_v2_hungarian/gt_overlap_audit.json"
if os.path.exists(gt_audit_path):
    gt_audit = json.load(open(gt_audit_path))["summary"]
    L += ["\n## GT geometry caveat（新發現）",
          "- 目前 room GT geometry 不是直接 `.house` floor polygon；它是 `regionN.ply` 全部 vertices 投影 XY→5cm raster closing/fill→external contour→10cm RDP。",
          f"- 目前 frozen GT polygon overlap＝**{100*gt_audit['current_polygon_overlap_ratio']:.2f}%**；直接 `.house` floor polygons＝**{100*gt_audit['house_floor_overlap_ratio']:.2f}%**。",
          f"- 同 room ID 兩種表示 mean IoU＝**{gt_audit['current_vs_house_mean_iou']:.3f}**。因此 overlap 主要是 GT 衍生流程造成。",
          "- 本輪不替換 GT、不改 headline scores；完整 audit 見 `docs/gt_overlap_audit.md`。"]

L += ["\n## 直接評估：夠不夠撐 attribute layer？",
      f"- 粗粒度房級（**有初步訊號**）：Room F1 {agg('A','room')['f1']:.2f}、matched-room 條件 IoU {np.mean(alliou):.2f}",
      "- 這不代表目前已足以直接掛接下游 attributes；仍需依研究容錯範圍做 downstream validation。",
      f"- 邊界精度（不足）：Corner@0.1m {agg('A','corner@0.1')['f1']:.2f}",
      f"- 連通（不足）：edge_all {agg('C','all')['f1']:.2f}", f"- 房型（不足）：{agg('B','room+type')['f1']:.2f}",
      "\n> v1_greedy→v2_hungarian 數值差異＝0（room IoU>0.5 下 greedy≈hungarian）；此版價值在 determinism。對照見 `outputs/eval2d/baselines/watershed_v3_pre_report/eval2d_v2_hungarian/comparison_v1_v2.json`。"]
open(f"{BASE}/eval2d_v2_hungarian/RESULTS_2D_regenerated.md", "w").write("\n".join(L))
print(f"[Task E] 四圖 → {VIZ}")
for t, p in vp.items(): print(f"  {t}: {os.path.basename(p)}")
print(f"  error analysis: {os.path.basename(error_fig)}")
print("archived v2 report regenerated；未覆寫 current RESULTS_2D.md")
